### ISSUE TITLE
percentage agreement is more than 100% when observers disagree on all cases irr::agree

### ISSUE THREAD

**Issue by cmetek** [sbalci/meddecide#1]
when you have say 40 observations with the first and second observer being complete opposite of each other, the module outputs 200% agreement, but when they agree on a single observation the 200% becomes 2.5%.

**Comment by sbalci** [comment]
would you please send the example file and the output

**Comment by cmetek** [comment]
[200percent bug.pdf](https://github.com/sbalci/meddecide/files/8365290/200percent.bug.pdf) 
[200percent bug.xlsx](https://github.com/sbalci/meddecide/files/8365311/200percent.bug.xlsx)

GitHub doesn't allow to upload OMV files, so I uploaded as an XLSX

**Comment by sbalci** [comment]
I think the authors of `irr` package have not thought of this much disagreement.
The result is 300 if you go with 3 observers.

```r
Rater1 <- c(rep("a",20), rep("b",20), rep("c",20))
Rater2 <- c(rep("b",20), rep("c",20), rep("a",20))
Rater3 <- c(rep("c",20), rep("a",20), rep("b",20))
mydata <- cbind(Rater1, Rater2, Rater3)
irr::agree(mydata)
result1 <- irr::agree(mydata)
result1[["value"]]
```

This is the `irr::agree()` function. It calculates numeric and character data differently. 

```r
"agree" <-
function(ratings, tolerance=0) {
  ratings <- as.matrix(na.omit(ratings))
  ns <- nrow(ratings)
  nr <- ncol(ratings)

  if (is.numeric(ratings)) {
    rangetab <- apply(ratings,1,max)-apply(ratings,1,min)
    coeff <- 100*sum(rangetab<=tolerance)/ns
  }
  else {
    rangetab <- as.numeric(sapply(apply(ratings,1,table),length))
    coeff <- 100*(sum(rangetab==1)/ns)
    tolerance <- 0
  }
	
  rval <- structure(list(method = paste("Percentage agreement (Tolerance=",tolerance,")",sep=""),
                         subjects = ns, raters = nr,
                         irr.name = "%-agree", value = coeff),
                    class="irrlist")
  return(rval)
}
```

The calculation relevant to what I indent is: 

```r
rangetab <- as.numeric(sapply(apply(ratings,1,table),length))
coeff <- 100*(sum(rangetab==1)/ns)
```

Here the function needs a checkpoint. If all `rangetab` has one value `length(unique(rangetab)) == 1` then there should be a warning or error.
