### ISSUE TITLE
IRR tables not accurate

### ISSUE THREAD

**Issue by evanmiltenburg** [sbalci/meddecide#3]
When using [this example data](https://github.com/sbalci/meddecide/files/11262684/voorbeeld_data.ods) I get tables that do not match the data:
<img width="141" alt="Screenshot 2023-04-18 at 16 12 18" src="https://user-images.githubusercontent.com/1513355/232804416-e6c355d0-008c-4ccc-8bd3-379708e9e6f9.png">

There are 45 Subjects, but the table only sums to 8. It works fine with two coders, but it seems the module cannot deal with three coders.

**Comment by sbalci** [comment]
Hi,

The following screenshots show the module in function. 
Would you please describe the data, I could not understand the names of the columns.



![Screenshot 2023-04-18 172621](https://user-images.githubusercontent.com/7208830/232809197-52077e7a-1abc-4029-85a0-6f463e040335.png)



![Screenshot 2023-04-18 172724](https://user-images.githubusercontent.com/7208830/232809237-c9cc2147-7eab-4c16-815e-0bfb46dcc357.png)

**Comment by sbalci** [comment]
The data should be organised as follows.
Each row should represent the subject that is rated (in my personal use it is the diagnosis).
Each column should be one observer (in my personal use, it is the scientist)
We write the  values given to each tumor by each scientist (rater) in the data.

The frequency table compares observers. When there are more than 2 raters the frequency table is separated to add the additional dimension.


![Screenshot 2023-04-18 181245](https://user-images.githubusercontent.com/7208830/232822091-8c4b316a-6c4d-409c-87b5-9dbea2c22215.png)


You can find the example data and example analysis as follows:

https://github.com/sbalci/ClinicoPathJamoviModule/raw/master/man/figures/jamovi-ClinicoPath-example-datasets.gif

**Comment by evanmiltenburg** [comment]
Right, but isn't that the same as what I did? Each row is a subject, each column is an observer, and the values are in the data (in my case: values between 1 and 5).

**Comment by sbalci** [comment]
In you case you should compare coder1, coder2, and coder3 for variable 1 as in the image below.
You have 45 cases, 3 coders, with 4% agreement.

![Screenshot 2023-04-18 184216](https://user-images.githubusercontent.com/7208830/232830624-214c9be0-a8d6-4d53-9309-aff79e72ae0d.png)

**Comment by evanmiltenburg** [comment]
Right, so that is correct but the ascii-like tables directly below the "Table" header comparing the coders don't seem to be correct, because the values in the tables do not sum to 45. Or am I misinterpreting them?On 18 Apr 2023, at 17:45, Serdar Balcı ***@***.***> wrote:﻿
In you case you should compare coder1, coder2, and coder3 for variable 1 as in the image below.
You have 45 cases, 3 coders, with 4% agreement.

**Comment by sbalci** [comment]
Yes, that interpretation is correct. This table was just a temporary solution. I will try to make those tables via gtsummary. But it will take some more time.
